### ISSUE TITLE
Black screen upon boot.

### ISSUE THREAD

**Issue by Shoeboxcat** [Lumince/SwitchRoot-Q-Overclock#2]
Hi Lumince, I was able to install your mod with TWRP, but I can't get to my lock screen. It just hangs on a black screen. The uninstaller didn't revert this problem. I'm on the May 10th Android 10 build on an unpatched Switch. Also, what is the August 12th dev build you mentioned?

Nevermind. I hadn't performed the May 10th OTA update. All is functioning now. Thank you for your work!

**Comment by Lumince** [comment]
I added info about the dev builds from SwitchRoot if you also want to check that out!
Were you able to get booted up fine with this zip?
